### ISSUE TITLE
Let's connect!

### ISSUE THREAD

**Issue by YannikPeterMHP** [henrik-dmg/gma-android-project#28]
Hallo @henrik-dmg,

ich sehe du interessierst dich für IOS Entwicklung? Wir suchen aktuell in diesem Bereich neue Kollegen, welche Lust haben weiter in die Entwicklung einzusteigen. Ich arbeite bei MHP a Porsche Company. Wir sind im Bereich Automotive und Manufacturing unterwegs.
Wenn du mal Interesse an einer Tätigkeit bei uns hast, melde dich doch einfach bei mir per LinkedIn (linkedin.com/in/yannik-peter] oder Mail: [yannik.peter@mhp.com](mailto:yannik.peter@mhp.com).

Beste Grüße,
Yannik

**Comment by henrik-dmg** [comment]
Moin Yannik,
Auch wenn ich dir für das Angebot dankbar bin, ist Github Issues absolut kein angebrachter Ort um mich zu kontaktieren. Auf meinem Profil sind klar sichtbar meine Email, Website und Twitter-Profil verlinkt.
